### ISSUE TITLE
Very odd behavior with notification to particular secondary/@sign

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_tools#85]
**Describe the bug**
When trying to send a notification from or too @realisticforeign results in the verb handler not finding a match ??

**To Reproduce**
1. Connect to a secondary'
2. AUthenticate
3. use the notify verb to notify the @realisticforeign @sign 
4. see the logs 

**Expected behavior**
Should not error and should be able to send a notification

```
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | FINER|2021-07-16 21:17:23.499330|AtSecondaryServer|inside _executeVerbCallBack: notify:notifier:system:@colin:location.wavi@realisticforeign
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | FINER|2021-07-16 21:17:23.499382|DefaultVerbExecutor|verb handler found : Null
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | SEVERE|2021-07-16 21:17:23.499387|DefaultVerbExecutor|No handler found for command: notify:notifier:system:@colin:location.wavi@realisticforeign
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #0      DefaultVerbExecutor.execute (package:at_secondary/src/verb/executor/default_verb_executor.dart:24)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #1      AtSecondaryServerImpl._executeVerbCallBack (package:at_secondary/src/server/at_secondary_impl.dart:293)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #2      InboundMessageListener._messageHandler (package:at_secondary/src/connection/inbound/inbound_message_listener.dart:59)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #7      _StreamController._add (dart:async/stream_controller.dart:607)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #8      _StreamController.add (dart:async/stream_controller.dart:554)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #9      _Socket._onData (dart:io-patch/socket_patch.dart:2160)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #14     _StreamController._add (dart:async/stream_controller.dart:607)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #15     _StreamController.add (dart:async/stream_controller.dart:554)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #16     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | SEVERE|2021-07-16 21:17:23.499610|AtSecondaryServer|Instance of 'InvalidSyntaxException'
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | FINER|2021-07-16 21:17:23.499672|InboundConnectionImpl|InternetAddress('10.10.89.89', IPv4):33430 Disconnected
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | SEVERE|2021-07-16 21:30:00.016512|AtCompactionJob|Instance of 'AtAccessLog' starting
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    | SEVERE|2021-07-16 21:45:00.016666|AtCompactionJob|Instance of 'AtAccessLog' starting
ba46657d-227b-5ecf-ad16-161f80249772_secondary.1.88yoj2nfii74@hornet-07    |
```
Also fails when sending from @colin 

```

cconstab@cally:~/@colin$ openssl s_client -ign_eof -brief 79b6d83f-5026-5fda-8299-5a0704bd2416.hornet.atsign.zone:1029
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = 79b6d83f-5026-5fda-8299-5a0704bd2416.hornet.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@from:@colin
data:_fea4710e-6b1f-40ae-a363-1079690507ed@colin:a413fc78-bbec-46d0-8866-324353ceffae
@pkam:DMyYArOI0de8ATOlCI3FVJFlmUGLSnG4UuDoPQWcNAb0IUeYhS0CCossacC6vLC5swnY6L7EoDsXjI7FsKTFKbdvbG+SREtQ4mHbh4AXeUJf3aPBtnehuJX2oxZC1s75krS6kUtsfhsSVvT8RJpmZN6rDTpiaOrXoQ6UfsnB4V/kDJ9R0YQneU+mKKWglD+Ub+owRODn3pXu9D21gWuYPLyU5j9cPLRaW8m8iZYyyZCBKqytJ9pMMYznll8O5tjaCfw1tFAb+ZegrsJgYdAjVWRcEFp4Uhfuoq6jLeBfKn8fkdk2+JEnoQAFhO1fCXF3R1cNM9fGpxfc89ZdImutwg==
data:success
@colin@notify:notifier:system:@spiderdeveloped:location.wavi@colin
data:e5c1b863-afd1-479c-af07-80b0aaa8d9df
@colin@notify:notifier:system:@realisticforeign:location.wavi@colin
error:AT0003-Invalid syntax : invalid command
@colin@CONNECTION CLOSED BY SERVER
cconstab@cally:~/@colin$

```

```
9b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |  key : _37525f22-ccce-458c-a5f4-676fead2c0d5@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.635284|LookupVerbHandler|lookup_key in lookupVerbHandler : public:_37525f22-ccce-458c-a5f4-676fead2c0d5@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.635309|Secondary_Util|result : bGBLfhP3/KT7LDgDVrDrrYe0+NnUcAxpv2fGTZqM4jlOJgLi7nTPKskOFJfbt0XUZloBBtQe8KQo95Pt690YRqL4fg/VMaNLD/3BezeoEc0mmasgTS9YkI2lpq/ehqTP6b6I4mL5b+dpcCH5uw3c7bUtCiNveUYIyNWcTV4BDhKoodIvaA/jsXL+A9J8/ZP0+AKmTNfQ3CFTDmgQNOCK7hJS5wUWuFn1ayf8bcCP1wXA/ech1sbjthPwBuBwkglSG5VmB/KF0fDUO/Z31FabQjw+Vi6vvsKhZj6AbOhBSxXQmjVItxbw/dUs4ORc9nR5wA8/tPDCYHjJmsve8LiFtw==
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.635320|LookupVerbHandler|Verb : lookup  Response: Response{_data: bGBLfhP3/KT7LDgDVrDrrYe0+NnUcAxpv2fGTZqM4jlOJgLi7nTPKskOFJfbt0XUZloBBtQe8KQo95Pt690YRqL4fg/VMaNLD/3BezeoEc0mmasgTS9YkI2lpq/ehqTP6b6I4mL5b+dpcCH5uw3c7bUtCiNveUYIyNWcTV4BDhKoodIvaA/jsXL+A9J8/ZP0+AKmTNfQ3CFTDmgQNOCK7hJS5wUWuFn1ayf8bcCP1wXA/ech1sbjthPwBuBwkglSG5VmB/KF0fDUO/Z31FabQjw+Vi6vvsKhZj6AbOhBSxXQmjVItxbw/dUs4ORc9nR5wA8/tPDCYHjJmsve8LiFtw==, _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.635328|DefaultResponseHandler|Got response: Response{_data: bGBLfhP3/KT7LDgDVrDrrYe0+NnUcAxpv2fGTZqM4jlOJgLi7nTPKskOFJfbt0XUZloBBtQe8KQo95Pt690YRqL4fg/VMaNLD/3BezeoEc0mmasgTS9YkI2lpq/ehqTP6b6I4mL5b+dpcCH5uw3c7bUtCiNveUYIyNWcTV4BDhKoodIvaA/jsXL+A9J8/ZP0+AKmTNfQ3CFTDmgQNOCK7hJS5wUWuFn1ayf8bcCP1wXA/ech1sbjthPwBuBwkglSG5VmB/KF0fDUO/Z31FabQjw+Vi6vvsKhZj6AbOhBSxXQmjVItxbw/dUs4ORc9nR5wA8/tPDCYHjJmsve8LiFtw==, _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677178|InboundListener|command received: lookup:signing_publickey@colin sessionID:_fd5a64ac-c9cc-4b22-8a05-4d357600be2b
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677327|AtSecondaryServer|inside _executeVerbCallBack: lookup:signing_publickey@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677399|DefaultVerbExecutor|verb handler found : LookupVerbHandler
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677456|LookupVerbHandler|fromAtSign : null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |  atSign : @colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |  key : signing_publickey@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677472|LookupVerbHandler|lookup_key in lookupVerbHandler : public:signing_publickey@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.677500|Secondary_Util|result : MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnphQ3MeUxV+mILYHBB1h7nPUWtpmi5XikB9HTtXQJvzr6Z7/r5PJq1tuilyUDwXoN+ZiVJXwyEgiYbraSccM31fLt/SM87E60FVfforkm6B4X05oFHZclHJpB/q9S+uKZtROm/jprqnmTgpnMHXmmWUKJAmTVvktA/tfGmhosDsE1mjIv3QsOY0bcvMoHKVLBrvFxHyG36IO8h3Pn/zFNmUFncTZUFG41Dv1Cx7ghgJAGs7smlZCuT3tfm2t22Rm3sKF9t5iSH7YAfYbERc53tRJ4e2iqxFhhCo7FO5ry6i14VAEVrfEH+Im0KWeO2gYSZHTNn7mGL8G5hJ/WT58YQIDAQAB
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.678015|LookupVerbHandler|Verb : lookup  Response: Response{_data: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnphQ3MeUxV+mILYHBB1h7nPUWtpmi5XikB9HTtXQJvzr6Z7/r5PJq1tuilyUDwXoN+ZiVJXwyEgiYbraSccM31fLt/SM87E60FVfforkm6B4X05oFHZclHJpB/q9S+uKZtROm/jprqnmTgpnMHXmmWUKJAmTVvktA/tfGmhosDsE1mjIv3QsOY0bcvMoHKVLBrvFxHyG36IO8h3Pn/zFNmUFncTZUFG41Dv1Cx7ghgJAGs7smlZCuT3tfm2t22Rm3sKF9t5iSH7YAfYbERc53tRJ4e2iqxFhhCo7FO5ry6i14VAEVrfEH+Im0KWeO2gYSZHTNn7mGL8G5hJ/WT58YQIDAQAB, _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.678057|DefaultResponseHandler|Got response: Response{_data: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnphQ3MeUxV+mILYHBB1h7nPUWtpmi5XikB9HTtXQJvzr6Z7/r5PJq1tuilyUDwXoN+ZiVJXwyEgiYbraSccM31fLt/SM87E60FVfforkm6B4X05oFHZclHJpB/q9S+uKZtROm/jprqnmTgpnMHXmmWUKJAmTVvktA/tfGmhosDsE1mjIv3QsOY0bcvMoHKVLBrvFxHyG36IO8h3Pn/zFNmUFncTZUFG41Dv1Cx7ghgJAGs7smlZCuT3tfm2t22Rm3sKF9t5iSH7YAfYbERc53tRJ4e2iqxFhhCo7FO5ry6i14VAEVrfEH+Im0KWeO2gYSZHTNn7mGL8G5hJ/WT58YQIDAQAB, _type: null, _isError: false, _errorMessage: null}
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.733252|InboundConnectionImpl|InternetAddress('10.10.0.6', IPv4):40990 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.759443|OutboundClient|handShakeResult: @colin@
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.759504|NotificationResourceManager|connect result: true
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.759531|OutboundClient|notificationRequest : notify:messageType:key:notifier:system:@spiderdeveloped:location.wavi@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.759647|OutboundClient|waiting for response from outbound connection
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.810323|OutboundClient|notifyResult result after format: data:success
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.810389|NotificationResourceManager|notifyResult : data:success
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.810728|OutboundClient|notificationRequest : notify:messageType:key:notifier:system:@spiderdeveloped:location.wavi@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.810826|OutboundClient|waiting for response from outbound connection
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.861313|OutboundClient|notifyResult result after format: data:success
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | INFO|2021-07-16 22:38:43.861372|NotificationResourceManager|notifyResult : data:success
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:38:43.862100|OutboundConnectionImpl|InternetAddress('34.121.142.209', IPv4):2490 Disconnected
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:39:09.484549|InboundListener|command received: notify:notifier:system:@realisticforeign:location.wavi@colin sessionID:_fea4710e-6b1f-40ae-a363-1079690507ed
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:39:09.484679|AtSecondaryServer|inside _executeVerbCallBack: notify:notifier:system:@realisticforeign:location.wavi@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:39:09.484752|DefaultVerbExecutor|verb handler found : Null
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | SEVERE|2021-07-16 22:39:09.484757|DefaultVerbExecutor|No handler found for command: notify:notifier:system:@realisticforeign:location.wavi@colin
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #0      DefaultVerbExecutor.execute (package:at_secondary/src/verb/executor/default_verb_executor.dart:24)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #1      AtSecondaryServerImpl._executeVerbCallBack (package:at_secondary/src/server/at_secondary_impl.dart:293)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #2      InboundMessageListener._messageHandler (package:at_secondary/src/connection/inbound/inbound_message_listener.dart:59)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #7      _StreamController._add (dart:async/stream_controller.dart:607)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #8      _StreamController.add (dart:async/stream_controller.dart:554)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #9      _Socket._onData (dart:io-patch/socket_patch.dart:2160)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #14     _StreamController._add (dart:async/stream_controller.dart:607)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #15     _StreamController.add (dart:async/stream_controller.dart:554)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #16     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | SEVERE|2021-07-16 22:39:09.485091|AtSecondaryServer|Instance of 'InvalidSyntaxException'
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    |
79b6d83f-5026-5fda-8299-5a0704bd2416_secondary.1.p8258pmdx9a9@hornet-09    | FINER|2021-07-16 22:39:09.485218|InboundConnectionImpl|InternetAddress('10.10.0.4', IPv4):39344 Disconnected

```

**Additional context**
Regex in at_tools/at_commons/lib/src/verb/syntax.dart when used standalone matches just fine

```
void main(List<String> arguments) {
  final verbRegex = RegExp(r'^notify:((?<operation>update|delete):)?(messageType:(?<messageType>key|text):)?(priority:(?<priority>low|medium|high):)?(strategy:(?<strategy>all|latest):)?(latestN:(?<latestN>\d+):)?(notifier:(?<notifier>[^\s:]+):)?(ttl:(?<ttl>\d+):)?(ttb:(?<ttb>\d+):)?(ttr:(?<ttr>(-)?\d+):)?(ccd:(?<ccd>true|false):)?(@(?<forAtSign>[^@:\s]*)):(?<atKey>[^:@]((?!:{2})[^@])+)(@(?<atSign>[^@:\s]+))?(:(?<value>.+))?$');
  if (verbRegex.hasMatch('notify:notifier:system:@spiderdeveloped:location.wavi@colin')){
    print("spider informed");// true
  }
  if (verbRegex.hasMatch('notify:notifier:system:@realisticforeign:location.wavi@colin')){
    print("realisticforeign informed");// true
  }
}
```

**Comment by cconstab** [comment]
I have put this as a P1 as I do not understand the issue or how wide the impact is.. Once it is understood and the impact is calculated feel free to move the priority down.

This is one ODD bug, reminds me of the double unicorn

**Comment by sitaram-kalluri** [comment]
Dev testing notes:
------------------------
@sitaram@notify:notifier:system:@realisticforeign:location.wavi@sitaram
data:a9901eaa-6da3-485c-8877-1db3d927beaa

**Comment by murali-shris** [comment]
> ## Dev testing notes:
> @sitaram@notify:notifier:system:@realisticforeign:location.wavi@sitaram
> data:a9901eaa-6da3-485c-8877-1db3d927beaa

@kalluriramkumar possible cause is notify syntax(or dependent code in at_commons) got changed and server is pointing to previous version..that may be the reason for command not found.

**Comment by murali-shris** [comment]
@cconstab can we close this issue?

**Comment by cconstab** [comment]
Closed fix confirmed..

**Comment by cconstab** [comment]
This was an odd issue but can be closed as fixed now
